name: demo
version: 0.1.0
dependencies:
  - base >= 4.18.3
  - hspec
executables:
  calculator:
    main: Main.hs
    source-dirs: src
library:
  source-dirs: src
tests:
  calculator-test:
    main: calculator_spec.hs
    source-dirs: 
      - test
      - src
