name = "training"
description = "Project for Ada training exercises"
version = "0.1.0-dev"

authors = ["Jorge Ascencio"]
maintainers = ["Jorge Ascencio <yorchek@gmail.com>"]
maintainers-logins = ["yorche3"]
licenses = "MIT"
website = ""
tags = []

[[depends-on]]
aunit = "^24.0.0"
