// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function fibonacci(n) {
  if (n <= 1) {
    return n;
  } else {
    return fibonacci(n - 1 | 0) + fibonacci(n - 2 | 0) | 0;
  }
}

function factorial(n) {
  if (n !== 1) {
    return Math.imul(n, factorial(n - 1 | 0));
  } else {
    return 1;
  }
}

function sum_numbers(n) {
  if (n !== 0) {
    return n + sum_numbers(n - 1 | 0) | 0;
  } else {
    return 0;
  }
}

exports.fibonacci = fibonacci;
exports.factorial = factorial;
exports.sum_numbers = sum_numbers;
/* No side effect */
