local words = require("words")

describe("Words Suite", function()
    it("reverse string", function()
        assert.are.equal("olleh", words.reverse_string("hello"))
        assert.are.equal("a", words.reverse_string("a"))
        assert.are.equal("", words.reverse_string(""))
    end)

    it("is palindrome", function()
       assert.is_true(words.is_palindrome("race car"))
       assert.is_true(words.is_palindrome("level"))
       assert.is_false(words.is_palindrome("hello"))
       assert.is_true(words.is_palindrome("a"))
       assert.is_true(words.is_palindrome(""))
    end)

    it("is substring", function()
        assert.is_true(words.kmp_search("test", "this is a test"))
        assert.is_false(words.kmp_search("not", "this is a test"))
        assert.is_true(words.kmp_search("", "any string"))
        assert.is_true(words.kmp_search("abc", "abc"))
        assert.is_false(words.kmp_search("abc", "ab"))
    end)

    it("longest common subsequence", function()
        assert.are.equal(4, words.lcs("AGGTAB", "GXTXAYB"))
        assert.are.equal(3, words.lcs("ABC", "ABC"))
        assert.are.equal(0, words.lcs("ABC", "DEF"))
        assert.are.equal(0, words.lcs("ABC", ""))
        assert.are.equal(0, words.lcs("", "ABC"))
    end)
end)